### PR TITLE
Fix reordering records in a sortable section

### LINKED ISSUE #38: Reordering new records in sortable sections fails
## Repro

* vapid new foo
* update index.html to add a new sortable section
* on the dashboard, add two new records for that section (let's say "one" and "two")
* drag the bottom record to the top (drag "one" to the top of the list)

## Expected

The dashboard and the site (and the db) match ordering.

## Actual

The dashboard shows "one" first but the site shows "two" first.

## Notes

Starting with a new section we add a new record "one", we have:

```
sqlite> select content, position from records;
{"repro":"one"}|0
```

then we add "two":

```
sqlite> select content, position from records;
{"repro":"one"}|0
{"repro":"two"}|0
```

At this point the dashboard is showing "two" first and "one" second. So we drag "one" to the top of the list and then we see this:

```
sqlite> select content, position from records;
{"repro":"one"}|1
{"repro":"two"}|0
```

Which is not correct. Refreshing the dashboard resets the UI order and reordering will work correctly up until a new record is added.

When new records are created in sortable sections they are given a position of 0 but the rest of the records associated with that section are not reordered, which results in this behavior. However, if the rest of the records are reordered then adding new records will take linearly longer as the list gets longer. A potential fix would be to use reverse ordering so that new records are always added with a position of length_of_section+1 and then the dashboard and site display the items in descending order. There might be other better options.

There a secondary related issue which creates gaps in the ordering - ordering forward shifts position up by 1 which means ordering forward then ordering backward creates an ordering gap. To see this in action create three records in a section and then move the top item to the bottom several times then move the bottom item up one. You'll see something like:

```
sqlite> select content, position from records;
{"repro":"one"}|4
{"repro":"two"}|7
{"repro":"three"}|6
```

This doesn't cause any visible issues I could see but I bet there are good reasons you don't want this.

### PR DESCRIPTION
**Pull request by srobbin**
Fixes #38

* Appends new sortable records to the end of the list
* Added factories for testing

Co-authored-by: Tres Henry <tres@treshenry.net>
Co-authored-by: Scott Robbin <scott@robbin.co>

### CODE REVIEW

**Comment by srobbin** [comment]
@ohnoimdead This should be good to go. No rush though. Enjoy your vacation, and we'll pick up on this afterward.

On a related note, I added you as a co-author to the PR, which requires us to [include our emails in the commit message](https://help.github.com/articles/creating-a-commit-with-multiple-authors/) (which I got from your GitHub profile). Let me know if that's OK, or if you'd prefer to not have that info in there.

File: lib/services/record_position_updater.js [hunk 1]
```diff
@@ -19,6 +26,11 @@ class RecordOrderUpdater {
     return this.section.getRecords({ order: [['position', 'ASC']] });
   }
 
+  async _append() {
+    const maxPosition = Utils.chain(this.siblings).map(s => s.position).max().value();
```
Comment (ohnoimdead) [inline lib/services/record_position_updater.js]: I think there's still a shlemiel the painter problem here where inserts will take linearly longer based on the length of the records in the section, however, it might not even be noticeable until you get to millions of records so *shrug*. One potential optimization for this solution might be something like `select max(position) from records where section_id = n;` and adding 1 instead of selecting all records in the section and then mapping for max position.

**Comment by ohnoimdead** [comment]
Also, southern Italy was beautiful and vacation was very much enjoyed. :D

img_0080

File: lib/services/record_position_updater.js (hunk 1 above)
Comment (srobbin) [reply lib/services/record_position_updater.js]: Good point. I just pushed a change to use `Record.max`.

File: lib/services/record_position_updater.js [hunk 2]
```diff
@@ -27,7 +27,9 @@ class RecordPositionUpdater {
   }
 
   async _append() {
-    const maxPosition = Utils.chain(this.siblings).map(s => s.position).max().value();
+    const { Record } = this.record.sequelize.models;
+    const maxPosition = await Record.max('position', { where: { section_id: this.section.id } });
```
Comment (ohnoimdead) [inline lib/services/record_position_updater.js]: ❤️
