### PR TITLE
Checks to see if port is in use before starting server

### LINKED ISSUE #5: Cannot exit when port in use
I couldn't close the program with Ctrl+C

Possible solution: https://github.com/Rich-Harris/port-authority

```
==> Starting the development server...
==> Watching for changes in /.../www
View your website at http://localhost:3000
Ctrl + C to quit
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Server.listen (livereload/lib/livereload.js:80:28)
    at Object.exports.createServer (livereload/lib/livereload.js:246:14)
    at Watcher.listen (vapid-cli/lib/watcher.js:35:22)
    at Vapid.start (vapid-cli/lib/vapid.js:150:20)
    at <anonymous>
Emitted 'error' event at:
    at Server.onError (livereload/lib/livereload.js:99:19)
    at WebSocketServer.emit (events.js:180:13)
    at Server.WebSocketServer._onServerError (livereload/node_modules/ws/lib/WebSocketServer.js:82:50)
    at Server.emit (events.js:180:13)
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

### PR DESCRIPTION
**Pull request by srobbin**
## Status
Ready

## Migrations
No

## Description
Adds a PortChecker service that checks to see if a port is in use before starting the Vapid server.

## Related Bugs
Fixes #5

## Steps to Reproduce

1. Start a vapid server in one terminal window.
2. Open a second terminal window, and launch another server (`bin/cli.js start .` to use the local/PR copy)
3. You should see an error message saying that the "port is already in use".
4. Application will safely exit.

### CODE REVIEW

File: bin/cli.js [hunk 1]
```diff
@@ -53,6 +54,12 @@ program
   .command('start')
   .description('start the server')
   .action(withVapid(async (vapid) => {
+    const portInUse = new services.PortChecker(vapid.config.port).perform();
```
Comment (ohnoimdead) [inline bin/cli.js]: missing an await here, should be: `await new services.PortChecker(`...

File: bin/cli.js [hunk 2]
```diff
@@ -53,6 +54,12 @@ program
...
+
+    if (portInUse) {
```
Comment (ohnoimdead) [inline bin/cli.js]: this will always be true because of the above

File: bin/cli.js (hunk 1 above)
Comment (srobbin) [reply bin/cli.js]: @ohnoimdead Good catch, thank you.
